language: node_js
sudo: false
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
- stable
- '4.3'
- iojs

before_script:
- npm install grunt-cli -g

after_script:
  - codeclimate-test-reporter < lcov.info

addons:
  code_climate:
    repo_token: 
      secure: "guIWEgG372FliskYf7Y5FGlcM+F5MXEdvRkMLc8AimHw4H6nPOH7I/zKo18WtBxvXbOz8GORgV0MkH7PYNlnG6F4b0EynzLb1kDDpiKFe+zaOidC6us6k2wV13HZcn8RJdg44tFbvhQhOgxWtxn6cLe6hYJcZjrpUz7FWE/GPgPsLgvSIOYoiEQpSg6yqHL8IGrHVDXbM9vXpq7fd5q1sQhbtQnR9Yo6e/lJA5Yd36N34aRl+p9X1S9IBUUD4+wZ1qLGvFp2tqdv8hxpxAsRQTTWVY1n4QuZvEf/VAv33tNLwnvS4W1x89EFzguoO6ib6HLsthl1aEq8H+jLg0OkYqdmEPS6gf4OqByNANsobV/Mlm+McNWs1GtWxFM/Dzw3OiEmFJiitk144hc9+icB0Rpb3eP+BPwFxueS2YEgV2GpZ4bnfpyI+YC91QM2uPpE1mUsz3kdc81V4Ji2mFaKl3cjaMuUw1UOc1C0+0Lmie3tXTmaV4oXTM52rLZFGD1CrEv3PB4VOMapyCD3kXHv3k6h/9UCWoqmacvFNuFTwZMUCBLYbgx6cyiWWusM3ETcxCqHtyCj6rJG8rS8zifSt1nc4qr3BNZPvIeB6br1E+lprvz91lXlWCRoT/VBQ6q+dy6GXEeG54KRnArpnaQjshtM0ck3dQBmwqS7M9C/KOY="

notifications:
  slack:
    secure: bOvtmHNtyPDIRfjt2IOtROJasbIPW5czQmggrUIQ4dENh4DIFXSQKdk9ptADcZHu04JEL6xl4Jpev4Jk8fIF92AjPR75hyyQUcdcgk9VVjVCqDogxLfioBZwhbfceQyqMdoetBOE+cLL/FP03oMOmRx5nrPF4ichsV5rAtp8vFOFZCgKVmjHmwZJEzRpl8dezwQEVMWzlKkYlgKyEyyNGGUAcgloc9ItNP3p4vgbBI/TTqTu8gtvfEUEqTL4Hk6XRVzHrNRI9bg00my1t/EOXiF2fu6LpZpzJu8yOw01ZfNw+YTOcqVTC++wCENfIDiewF334SKUJVkfQBqnBmsrwqkXXvpbe55YYN4dn2rY+wxF/3dj0/N4Z2+OLPfNXGUUIhBg6r9JVZRjrvs9cNgbKYhkrf7UkzBYhuSKJ7lvetDtE93qhpw8p+MemsXOtYhTLNvPh/FetJt0ZEhxyCgXCtufgPlnldn/sdjuJoA5bj7Nnh3DP0lFF4Vzx9y4JdbyBav9O/t6FLIAiKXq/6zsMxmYNcW+12zVyxYBsMIPtjtdfrj3i4lfR7vRl2ozgAEiPhG+/d5ahFVFFrMQvD+esInI/kLXgwqe5ejyw/jZbEBRKtuYZdTK6be15mBcLYDibmrfEmVUh05LA1/bmjZFN9x/95bMdlWm4oUwM0QER98=

